Repository Semantic-Society/Neologism, pull requests merged in 2021-06, with the labels that each got.

#192 Add pages website
  _config.yml
Labels: documentation

#191 Update Angular, Meteor, Node, and dependencies
  Dockerfile
  app/angular.json
  app/api/.meteor/packages
  app/api/.meteor/release
  app/api/.meteor/versions
  app/api/models.ts
  app/api/package-lock.json
  app/api/server/helper.ts
  app/api/server/methods.ts
  app/api/server/publications.ts
  app/api/server/routes.ts
  app/api/tsconfig.json
  app/package-lock.json
  app/package.json
  app/src/app/angular2-material-meteor-accounts-ui/accounts-module.ts
  app/src/app/angular2-material-meteor-accounts-ui/validation.service.ts
  app/src/app/app.component.spec.ts
  app/src/app/app.module.ts
  app/src/app/batchRecommender/batchRecommender.component.spec.ts
  app/src/app/editbox/editbox.component.spec.ts
  app/src/app/editbox/editbox.component.ts
  app/src/app/editbox/editbox.service.ts
  app/src/app/home-dashboard/create-vocab-modal/create-vocab-modal.component.spec.ts
  app/src/app/home-dashboard/home-dashboard.component.spec.ts
  app/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.spec.ts
  app/src/app/login-page/login-page.component.spec.ts
  app/src/app/metadata/metadata.component.spec.ts
  app/src/app/metadata/metadata.component.ts
  app/src/app/models/editbox.model.ts
  app/src/app/mxgraph/N3Codec.ts
  app/src/app/mxgraph/mxgraph.component.spec.ts
  app/src/app/mxgraph/mxgraph.component.ts
  app/src/app/mxgraph/mxgraph.ts
  app/src/app/mxgraph/property-edit-form/property-edit.component.ts
  app/src/app/mxgraph/standardView/standardView.component.spec.ts
  app/src/app/ng-zorro.module.ts
  app/src/app/recommender/recommender.component.spec.ts
  app/src/app/recommender/recommender.component.ts
  app/src/app/routing.module.ts
  app/src/app/search-vocabularies-autocomplete/search-vocabularies-autocomplete.component.spec.ts
  app/src/app/services/BatchQuery.ts
  app/src/app/services/BatchRecommendations.ts
  app/src/app/services/Recommendation.ts
  app/src/app/services/access-management.service.ts
  app/src/app/services/recommendation.service.spec.ts
  app/src/app/services/recommendation.service.ts
  app/src/app/services/state-services/sidebar-state.service.ts
  app/src/app/services/vocabularies.service.ts
  app/src/app/truncated-text-component/truncated-text-component.component.spec.ts
  app/src/app/vocablist/components/add-user-modal/add-user-modal.component.spec.ts
  app/src/app/vocablist/vocablist.component.spec.ts
  app/src/app/vocabulary-editor/list-editor/list-editor.component.spec.ts
  app/src/app/vocabulary-editor/mx-graph-editor/mx-graph-editor.component.spec.ts
  app/src/app/vocabulary-editor/vocabulary-editor.component.spec.ts
  app/src/environments/environment.ts
  app/src/polyfills.ts
  app/tsconfig.json
  app/tslint.json
Labels: critical, dependencies, enhancement

#198 removed btn and added anchor with editor
  app/src/app/app.module.ts
  app/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.html
  app/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.ts
  app/src/app/services/vocabularies.service.ts
Labels: bug, enhancement

#199 Removed npm and atmosphere pckgs
  app/api/.meteor/packages
  app/api/.meteor/versions
  app/package-lock.json
  app/package.json
  app/src/app/app.module.ts
Labels: compliance review

#194 166 move ci pipeline
  .github/workflows/Build And Publish Docker Image.yml
Labels: documentation, enhancement
